apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-soon-to-be-snapshotted-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: sbs-default
