apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-restored-snapshot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sbs-default
  resources:
    requests:
      storage: 5Gi
  dataSource:
    name: my-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
