linters:
  enable:
    - dupl
    - errname
    - ginkgolinter
    - goconst
    - godox
    - gosec
    - nilerr
    - prealloc
    - reassign
    - tparallel
    - wrapcheck

linters-settings:
 wrapcheck:
    ignorePackageGlobs:
      - google.golang.org/grpc/status
