name: merge
on:
  push:
    branches:
      - 'master'
      - 'release-*'
      - update-workflows
jobs:
  merge_master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.4.0
        with:
          context: .
          push: false
          tags: example.com/fake:latest
          platforms: linux/amd64,linux/arm/v7,linux/arm64
